# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myLoginUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(749, 482)
        Dialog.setMinimumSize(QtCore.QSize(749, 482))
        Dialog.setMaximumSize(QtCore.QSize(749, 482))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/images_test/bird-logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 747, 483))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btn_minimize = QtWidgets.QPushButton(self.frame)
        self.btn_minimize.setGeometry(QtCore.QRect(666, 8, 35, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_minimize.sizePolicy().hasHeightForWidth())
        self.btn_minimize.setSizePolicy(sizePolicy)
        self.btn_minimize.setMinimumSize(QtCore.QSize(25, 25))
        self.btn_minimize.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_minimize.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/login/icons/minmax.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_minimize.setIcon(icon1)
        self.btn_minimize.setObjectName("btn_minimize")
        self.label_movie = QtWidgets.QLabel(self.frame)
        self.label_movie.setGeometry(QtCore.QRect(6, 6, 321, 471))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_movie.sizePolicy().hasHeightForWidth())
        self.label_movie.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(16)
        self.label_movie.setFont(font)
        self.label_movie.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_movie.setStyleSheet("QLabel{\n"
"border-image: url(:/login/icons/person1.gif);\n"
"}")
        self.label_movie.setAlignment(QtCore.Qt.AlignCenter)
        self.label_movie.setObjectName("label_movie")
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        self.tabWidget.setGeometry(QtCore.QRect(326, 2, 417, 475))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("\n"
"QTabWidget::pane{\n"
"min-width:70px;\n"
"min-height:25px;\n"
"border-top: 0px solid;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"font-size:10px;\n"
"min-width:70px;\n"
"\n"
"min-height:25px;\n"
"\n"
"color: black;\n"
"\n"
"font:12px \"Microsoft YaHei\";\n"
"\n"
"border: -1px solid;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"QTabBar::tab:selected{\n"
"\n"
"min-width:70px;\n"
"\n"
"min-height:25px;\n"
"color: black;\n"
"\n"
"font:11px \"Microsoft YaHei\";\n"
"\n"
"border: 0px solid;\n"
"\n"
"border-bottom: 0px solid;\n"
"\n"
"border-color: #4796f0;\n"
"\n"
"}")
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_login = QtWidgets.QWidget()
        self.tab_login.setObjectName("tab_login")
        self.checkBox_remenber = QtWidgets.QCheckBox(self.tab_login)
        self.checkBox_remenber.setGeometry(QtCore.QRect(66, 272, 115, 35))
        self.checkBox_remenber.setStyleSheet("\n"
"QCheckBox{\n"
"font: 10pt \"微软雅黑\";\n"
"color: rgb(100, 100, 100);\n"
"spacing: 5px;\n"
"background-color: transparent;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"width: 18px;\n"
"height: 18px;\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"border-image: url(:/login/icons/check.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"border-image: url(:/login/icons/checked.png);\n"
"}\n"
" ")
        self.checkBox_remenber.setIconSize(QtCore.QSize(18, 18))
        self.checkBox_remenber.setChecked(True)
        self.checkBox_remenber.setObjectName("checkBox_remenber")
        self.lineEdit_password = QtWidgets.QLineEdit(self.tab_login)
        self.lineEdit_password.setGeometry(QtCore.QRect(100, 208, 261, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setText("")
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.label_log_passwordBack = QtWidgets.QLabel(self.tab_login)
        self.label_log_passwordBack.setGeometry(QtCore.QRect(52, 208, 319, 43))
        self.label_log_passwordBack.setStyleSheet("border-image: url(:/images/icons/logo1.png);")
        self.label_log_passwordBack.setText("")
        self.label_log_passwordBack.setObjectName("label_log_passwordBack")
        self.label_log_user = QtWidgets.QLabel(self.tab_login)
        self.label_log_user.setGeometry(QtCore.QRect(64, 146, 21, 21))
        self.label_log_user.setStyleSheet("border-image: url(:/login/icons/logo2.png);\n"
"background-color: transparent;")
        self.label_log_user.setText("")
        self.label_log_user.setObjectName("label_log_user")
        self.lineEdit_user_log = QtWidgets.QLineEdit(self.tab_login)
        self.lineEdit_user_log.setGeometry(QtCore.QRect(100, 136, 259, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_user_log.setFont(font)
        self.lineEdit_user_log.setText("")
        self.lineEdit_user_log.setObjectName("lineEdit_user_log")
        self.toolButton_forgetCode = QtWidgets.QToolButton(self.tab_login)
        self.toolButton_forgetCode.setGeometry(QtCore.QRect(252, 272, 121, 33))
        self.toolButton_forgetCode.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton_forgetCode.setIconSize(QtCore.QSize(16, 16))
        self.toolButton_forgetCode.setObjectName("toolButton_forgetCode")
        self.label_log_password = QtWidgets.QLabel(self.tab_login)
        self.label_log_password.setGeometry(QtCore.QRect(64, 220, 21, 21))
        self.label_log_password.setStyleSheet("border-image: url(:/login/icons/logo3.png);\n"
"background-color: transparent;")
        self.label_log_password.setText("")
        self.label_log_password.setObjectName("label_log_password")
        self.pushButton_login = QtWidgets.QPushButton(self.tab_login)
        self.pushButton_login.setGeometry(QtCore.QRect(76, 338, 261, 43))
        self.pushButton_login.setStyleSheet("QPushButton{\n"
"    background-color:rgb(26, 122, 244);\n"
"    border-radius:10px; \n"
"    border:1px;\n"
"    font:17px \"微软雅黑\";\n"
"    color:rgba(255,255,255);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    border-color:rgba(255,255,255,30);\n"
"    background-color: rgb(0, 170, 255);\n"
"    border-style:inset;\n"
"    color:rgba(0,0,0,100);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgb(73, 154, 237);\n"
"    border-color:rgba(255,255,255,200);\n"
"    color:rgba(255,255,255);\n"
"}")
        self.pushButton_login.setObjectName("pushButton_login")
        self.label_pic = QtWidgets.QLabel(self.tab_login)
        self.label_pic.setGeometry(QtCore.QRect(166, 16, 85, 85))
        self.label_pic.setMinimumSize(QtCore.QSize(85, 85))
        self.label_pic.setMaximumSize(QtCore.QSize(85, 85))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_pic.setFont(font)
        self.label_pic.setStyleSheet("border-image: url(:/login/icons/user.png);\n"
"background-color: transparent;\n"
"border-radius:40px;")
        self.label_pic.setText("")
        self.label_pic.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pic.setObjectName("label_pic")
        self.label_log_userBack = QtWidgets.QLabel(self.tab_login)
        self.label_log_userBack.setGeometry(QtCore.QRect(52, 136, 319, 43))
        self.label_log_userBack.setStyleSheet("border-image: url(:/images/icons/logo1.png);")
        self.label_log_userBack.setText("")
        self.label_log_userBack.setObjectName("label_log_userBack")
        self.toolButton_go2reg = QtWidgets.QToolButton(self.tab_login)
        self.toolButton_go2reg.setGeometry(QtCore.QRect(2, 408, 121, 41))
        self.toolButton_go2reg.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton_go2reg.setObjectName("toolButton_go2reg")
        self.label_log_info = QtWidgets.QLabel(self.tab_login)
        self.label_log_info.setGeometry(QtCore.QRect(162, 406, 179, 39))
        self.label_log_info.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 0, 127);\n"
"font: 9pt \"微软雅黑\";")
        self.label_log_info.setText("")
        self.label_log_info.setObjectName("label_log_info")
        self.label_log_passwordBack.raise_()
        self.label_log_userBack.raise_()
        self.checkBox_remenber.raise_()
        self.lineEdit_password.raise_()
        self.label_log_user.raise_()
        self.lineEdit_user_log.raise_()
        self.toolButton_forgetCode.raise_()
        self.label_log_password.raise_()
        self.pushButton_login.raise_()
        self.label_pic.raise_()
        self.toolButton_go2reg.raise_()
        self.label_log_info.raise_()
        self.tabWidget.addTab(self.tab_login, "")
        self.tab_reg = QtWidgets.QWidget()
        self.tab_reg.setObjectName("tab_reg")
        self.lineEdit_user_reg = QtWidgets.QLineEdit(self.tab_reg)
        self.lineEdit_user_reg.setGeometry(QtCore.QRect(100, 122, 259, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_user_reg.setFont(font)
        self.lineEdit_user_reg.setText("")
        self.lineEdit_user_reg.setObjectName("lineEdit_user_reg")
        self.label_reg_passwordBack = QtWidgets.QLabel(self.tab_reg)
        self.label_reg_passwordBack.setGeometry(QtCore.QRect(52, 192, 319, 43))
        self.label_reg_passwordBack.setStyleSheet("border-image: url(:/login/icons/logo1.png);")
        self.label_reg_passwordBack.setText("")
        self.label_reg_passwordBack.setObjectName("label_reg_passwordBack")
        self.label_reg_user = QtWidgets.QLabel(self.tab_reg)
        self.label_reg_user.setGeometry(QtCore.QRect(64, 132, 21, 21))
        self.label_reg_user.setStyleSheet("border-image: url(:/login/icons/logo2.png);\n"
"background-color: transparent;")
        self.label_reg_user.setText("")
        self.label_reg_user.setObjectName("label_reg_user")
        self.lineEdit_password_reg = QtWidgets.QLineEdit(self.tab_reg)
        self.lineEdit_password_reg.setGeometry(QtCore.QRect(100, 192, 261, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_password_reg.setFont(font)
        self.lineEdit_password_reg.setText("")
        self.lineEdit_password_reg.setObjectName("lineEdit_password_reg")
        self.label_pic_reg = QtWidgets.QLabel(self.tab_reg)
        self.label_pic_reg.setGeometry(QtCore.QRect(166, 10, 85, 85))
        self.label_pic_reg.setMinimumSize(QtCore.QSize(85, 85))
        self.label_pic_reg.setMaximumSize(QtCore.QSize(85, 85))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_pic_reg.setFont(font)
        self.label_pic_reg.setStyleSheet("border-image: url(:/login/icons/user.png);\n"
"background-color: transparent;\n"
"border-radius:40px;")
        self.label_pic_reg.setText("")
        self.label_pic_reg.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pic_reg.setObjectName("label_pic_reg")
        self.toolButton_go2login = QtWidgets.QToolButton(self.tab_reg)
        self.toolButton_go2login.setGeometry(QtCore.QRect(2, 408, 119, 39))
        self.toolButton_go2login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton_go2login.setObjectName("toolButton_go2login")
        self.label_reg_password = QtWidgets.QLabel(self.tab_reg)
        self.label_reg_password.setGeometry(QtCore.QRect(64, 204, 21, 21))
        self.label_reg_password.setStyleSheet("border-image: url(:/login/icons/logo3.png);\n"
"background-color: transparent;")
        self.label_reg_password.setText("")
        self.label_reg_password.setObjectName("label_reg_password")
        self.label_reg_userBack = QtWidgets.QLabel(self.tab_reg)
        self.label_reg_userBack.setGeometry(QtCore.QRect(52, 122, 319, 43))
        self.label_reg_userBack.setStyleSheet("border-image: url(:/login/icons/logo1.png);")
        self.label_reg_userBack.setText("")
        self.label_reg_userBack.setObjectName("label_reg_userBack")
        self.pushButton_reg = QtWidgets.QPushButton(self.tab_reg)
        self.pushButton_reg.setGeometry(QtCore.QRect(76, 340, 261, 43))
        self.pushButton_reg.setStyleSheet("QPushButton{\n"
"    background-color:rgb(26, 122, 244);\n"
"    border-radius:10px; \n"
"    border:1px;\n"
"    font:17px \"微软雅黑\";\n"
"    color:rgba(255,255,255);\n"
"}\n"
"\n"
"QPushButton::pressed{\n"
"    border-color:rgba(255,255,255,30);\n"
"    background-color: rgb(0, 170, 255);\n"
"    border-style:inset;\n"
"    color:rgba(0,0,0,100);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgb(73, 154, 237);\n"
"    border-color:rgba(255,255,255,200);\n"
"    color:rgba(255,255,255);\n"
"}")
        self.pushButton_reg.setObjectName("pushButton_reg")
        self.label_reg_vercodeBack = QtWidgets.QLabel(self.tab_reg)
        self.label_reg_vercodeBack.setGeometry(QtCore.QRect(52, 262, 223, 43))
        self.label_reg_vercodeBack.setStyleSheet("border-image: url(:/login/icons/logo1.png);")
        self.label_reg_vercodeBack.setText("")
        self.label_reg_vercodeBack.setObjectName("label_reg_vercodeBack")
        self.label_reg_vercode = QtWidgets.QLabel(self.tab_reg)
        self.label_reg_vercode.setGeometry(QtCore.QRect(64, 272, 21, 23))
        self.label_reg_vercode.setStyleSheet("border-image: url(:/login/icons/logo4.png);\n"
"background-color: transparent;")
        self.label_reg_vercode.setText("")
        self.label_reg_vercode.setObjectName("label_reg_vercode")
        self.lineEdit_code_reg = QtWidgets.QLineEdit(self.tab_reg)
        self.lineEdit_code_reg.setGeometry(QtCore.QRect(100, 262, 159, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.lineEdit_code_reg.setFont(font)
        self.lineEdit_code_reg.setText("")
        self.lineEdit_code_reg.setObjectName("lineEdit_code_reg")
        self.toolButton_verCode = QtWidgets.QToolButton(self.tab_reg)
        self.toolButton_verCode.setGeometry(QtCore.QRect(282, 262, 89, 43))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_verCode.sizePolicy().hasHeightForWidth())
        self.toolButton_verCode.setSizePolicy(sizePolicy)
        self.toolButton_verCode.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton_verCode.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/login/icons/captcha_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_verCode.setIcon(icon2)
        self.toolButton_verCode.setIconSize(QtCore.QSize(89, 43))
        self.toolButton_verCode.setObjectName("toolButton_verCode")
        self.label_reg_info = QtWidgets.QLabel(self.tab_reg)
        self.label_reg_info.setGeometry(QtCore.QRect(158, 408, 179, 39))
        self.label_reg_info.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 0, 127);\n"
"font: 9pt \"微软雅黑\";")
        self.label_reg_info.setText("")
        self.label_reg_info.setObjectName("label_reg_info")
        self.label_reg_userBack.raise_()
        self.lineEdit_user_reg.raise_()
        self.label_reg_passwordBack.raise_()
        self.label_reg_user.raise_()
        self.lineEdit_password_reg.raise_()
        self.label_pic_reg.raise_()
        self.toolButton_go2login.raise_()
        self.label_reg_password.raise_()
        self.pushButton_reg.raise_()
        self.label_reg_vercodeBack.raise_()
        self.label_reg_vercode.raise_()
        self.lineEdit_code_reg.raise_()
        self.toolButton_verCode.raise_()
        self.label_reg_info.raise_()
        self.tabWidget.addTab(self.tab_reg, "")
        self.btn_close = QtWidgets.QPushButton(self.frame)
        self.btn_close.setGeometry(QtCore.QRect(704, 8, 33, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_close.sizePolicy().hasHeightForWidth())
        self.btn_close.setSizePolicy(sizePolicy)
        self.btn_close.setMinimumSize(QtCore.QSize(25, 25))
        self.btn_close.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_close.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/login/icons/extractLeft.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon3)
        self.btn_close.setObjectName("btn_close")
        self.tabWidget.raise_()
        self.btn_minimize.raise_()
        self.label_movie.raise_()
        self.btn_close.raise_()

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_minimize.setToolTip(_translate("Dialog", "最小化"))
        self.label_movie.setToolTip(_translate("Dialog", "<html><head/><body><p>资源采矿小分队</p><p>微信：<a href=\"Lc1977203562\"><span style=\" text-decoration: underline; color:#0000ff;\">wuxian.blog.csdn.net</span></a></p><p> 联系方式：<a href=\"17391088807\"><span style=\" text-decoration: underline; color:#0000ff;\">资源采矿小分队</span></a></p></body></html>"))
        self.label_movie.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.checkBox_remenber.setText(_translate("Dialog", "记住密码"))
        self.toolButton_forgetCode.setText(_translate("Dialog", "忘记密码"))
        self.pushButton_login.setText(_translate("Dialog", "登 录"))
        self.toolButton_go2reg.setText(_translate("Dialog", "注册账号"))
        self.toolButton_go2login.setText(_translate("Dialog", "前往登录"))
        self.pushButton_reg.setText(_translate("Dialog", "注 册"))
        self.btn_close.setToolTip(_translate("Dialog", "关闭"))
import RecSystem_rc
